# Generated by Django 4.0.1 on 2022-02-28 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_articlecategory_articletype_delete_default_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleType',
            new_name='ArticleTemplate',
        ),
    ]
