# Generated by Django 4.0.1 on 2022-03-05 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_paragraph_created_at_paragraph_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article'},
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description_en',
            field=models.TextField(help_text='Short, interessting text for catching the reader', max_length=500, verbose_name='Short Description EN'),
        ),
    ]
