# Generated by Django 4.0.1 on 2022-02-28 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_rename_articletype_articletemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'Article Category'},
        ),
        migrations.AlterModelOptions(
            name='articletemplate',
            options={'verbose_name': 'Article Template'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='type',
            new_name='template',
        ),
    ]
