# Generated by Django 4.0.1 on 2022-02-28 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_articleimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimages',
            options={'verbose_name': 'Images of Article'},
        ),
    ]
