# Generated by Django 4.0.1 on 2022-03-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_rename_primary_image_source_article_primary_media_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='primary_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='article/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='article',
            name='primary_video',
            field=models.FileField(blank=True, default=None, help_text='Required format: MP4', null=True, upload_to='article/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description_en',
            field=models.TextField(help_text='Short, interessting text for catching the reader.', max_length=350, verbose_name='Short Description EN'),
        ),
    ]
