# Generated by Django 4.0.1 on 2022-04-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_publication_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='pub_copyright',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Copyright'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='List of Authors'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Publication Titel'),
        ),
    ]
