# Generated by Django 4.0.1 on 2022-01-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_partner_options_alter_partnertype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='title',
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(default='home/placeholder.png', upload_to='partneruploads/'),
        ),
    ]
