# Generated by Django 4.0.1 on 2022-01-16 16:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_partner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Select country')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='+90 141 4992834', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='partner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 1, 16, 16, 15, 18, 941288, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='partnertype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnertype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
