# Generated by Django 4.0.1 on 2022-01-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_partnertype_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='terms_accepted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subscription',
            name='phone',
            field=models.CharField(blank=True, default='393', help_text='Example: +90 141 4992834', max_length=20),
            preserve_default=False,
        ),
    ]
