# Generated by Django 4.0.1 on 2022-02-28 20:19

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_subscription_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, verbose_name='Country'),
        ),
    ]
