# Generated by Django 4.0.1 on 2022-04-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_subscription_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='internal_note',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, unique=True, verbose_name='Email'),
        ),
    ]
