# Generated by Django 4.0.1 on 2022-04-04 12:20

from django.db import migrations
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_subscription_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=home.models.EmailNullField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email'),
        ),
    ]
