# Generated by Django 4.0.1 on 2022-01-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_partner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='country',
            field=models.CharField(default='Germany', max_length=50),
            preserve_default=False,
        ),
    ]
