# Generated by Django 4.0.1 on 2022-01-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_partner_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(default='home/media/partneruploads/placeholder.png', upload_to='home/media/partneruploads/'),
        ),
    ]
