# Generated by Django 4.0.1 on 2022-01-16 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_subscription_partner_created_at_partner_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnertype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='partnertype',
            name='updated_at',
        ),
    ]
