# Generated by Django 4.0.1 on 2022-03-05 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Article Category',
            },
        ),
        migrations.CreateModel(
            name='ArticleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Article Template',
            },
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_image', models.ImageField(blank=True, default=None, help_text='Ratio Width=1 Height=1', null=True, upload_to='article/%Y/%m/%d')),
                ('paragraph_image_source', models.CharField(blank=True, max_length=150, verbose_name='Paragraph Image Source')),
                ('headline', models.CharField(max_length=300, verbose_name='Paragraph Headline')),
                ('description_en', models.TextField(max_length=10000, verbose_name='Description EN')),
                ('description_tr', models.TextField(blank=True, max_length=10000, verbose_name='Description TR')),
            ],
            options={
                'verbose_name': 'Paragraph',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Article Titel')),
                ('short_description_en', models.TextField(max_length=500, verbose_name='Short Description EN')),
                ('short_description_tr', models.TextField(blank=True, max_length=500, verbose_name='Short Description TR')),
                ('main_description_en', models.TextField(max_length=10000, verbose_name='Description EN')),
                ('main_description_tr', models.TextField(blank=True, max_length=10000, verbose_name='Description TR')),
                ('thumbnail', models.ImageField(default='article/placeholder.png', upload_to='article/')),
                ('primary_image', models.ImageField(blank=True, default=None, help_text='Ratio Width=1 Height=1', null=True, upload_to='article/%Y/%m/%d')),
                ('primary_image_source', models.CharField(blank=True, max_length=150, verbose_name='Primary Image Source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.articlecategory', verbose_name='Article Category')),
                ('paragraph', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='article.paragraph')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.articletemplate', verbose_name='Article Type')),
            ],
            options={
                'verbose_name': 'Article',
            },
        ),
    ]
