# Generated by Django 4.0.1 on 2022-03-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='paragraph',
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_paragraph', to='article.paragraph'),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_paragraph', to='article.paragraph'),
        ),
        migrations.AddField(
            model_name='article',
            name='paragraph3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_paragraph', to='article.paragraph'),
        ),
    ]
