# Generated by Django 4.0.1 on 2022-03-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_options_articlecategory_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='primary_image_source',
            new_name='primary_media_source',
        ),
        migrations.AddField(
            model_name='article',
            name='primary_video',
            field=models.FileField(blank=True, default=None, help_text='HTML Template is only for image OR video.', null=True, upload_to='article/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='article',
            name='primary_image',
            field=models.ImageField(blank=True, default=None, help_text='HTML Template is only for image OR video.', null=True, upload_to='article/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description_en',
            field=models.TextField(help_text='Short, interessting text for catching the reader', max_length=350, verbose_name='Short Description EN'),
        ),
        migrations.AlterField(
            model_name='article',
            name='short_description_tr',
            field=models.TextField(blank=True, max_length=350, verbose_name='Short Description TR'),
        ),
    ]
