# Generated by Django 4.0.1 on 2022-04-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_article_primary_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Publication Titel')),
                ('authors', models.CharField(max_length=200, verbose_name='List of Authors')),
                ('abstract', models.TextField(verbose_name='Abstract')),
                ('methods', models.TextField(verbose_name='Methods')),
                ('conclusion', models.TextField(verbose_name='Conclusion')),
                ('result', models.TextField(verbose_name='Result')),
                ('publication_as_file', models.FileField(blank=True, default=None, help_text='Recommended format: PDF', null=True, upload_to='article/%Y/%m/%d', verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
