# Generated by Django 4.0.1 on 2022-04-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(max_length=200, null=True, verbose_name='List of Authors'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='conclusion',
            field=models.TextField(null=True, verbose_name='Conclusion'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='methods',
            field=models.TextField(null=True, verbose_name='Methods'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='result',
            field=models.TextField(null=True, verbose_name='Result'),
        ),
    ]
