# Generated by Django 4.0.1 on 2022-05-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_publication_pub_copyright_alter_publication_authors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_as_file',
            field=models.FileField(blank=True, default=None, help_text='Recommended format: PDF', null=True, upload_to='article/%Y/%m/%d', verbose_name='Paper'),
        ),
    ]
