# Generated by Django 4.0.1 on 2022-06-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_alter_publication_publication_as_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(default='article/placeholder.png', upload_to='article/%Y/%m/%d'),
        ),
    ]
