# Generated by Django 4.0.1 on 2022-01-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_partner_delete_partners'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Partner'},
        ),
        migrations.AlterModelOptions(
            name='partnertype',
            options={'verbose_name': 'Partner Type'},
        ),
        migrations.AddField(
            model_name='partner',
            name='latitude',
            field=models.DecimalField(decimal_places=15, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='longitude',
            field=models.DecimalField(decimal_places=15, default=1, max_digits=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(default='partneruploads/placeholder.png', upload_to='partneruploads/'),
        ),
    ]
