# Generated by Django 4.0.1 on 2022-01-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_partner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='image',
            field=models.ImageField(default='home/media/uploads/placeholder.png', upload_to='home/media/uploads/'),
        ),
    ]
