# Generated by Django 4.0.1 on 2022-04-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_subscription_options_alter_subscription_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Phonenumber'),
        ),
    ]
